### ISSUE TITLE
Add NodeLocal DNSCache beta addon support

### ISSUE THREAD

**Issue by Dev25** [terraform-google-modules/terraform-google-kubernetes-engine#428]
[NodeLocal DNSCache](https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache) was recently promoted to beta, add a flag to enable it for beta modules.

Blocked until beta provider supports it, looking at the GKE REST API this should just be a simple [boolean flag](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.DnsCacheConfig)

**Comment by morgante** [comment]
Please make sure you open a provider issue as well.

**Comment by Dev25** [comment]
Existing Issue: https://github.com/terraform-providers/terraform-provider-google/issues/5150

**Comment by Dev25** [comment]
This is no longer blocked, [3.14](https://github.com/terraform-providers/terraform-provider-google/releases/tag/v3.14.0) was released yesterday that includes a `dns_cache_config` field.

**Comment by sebastianortizs4n** [comment]
This change always forces replacement of the cluster, even when is set to false and is also disabled on the cluster. This should not happen... Is the same configured value.

**Comment by morgante** [comment]
This seems like a bug in the provider, but we could probably make it a dynamic block.

**Comment by sebastianortizs4n** [comment]
@morgante  this is it, is solved already https://github.com/terraform-providers/terraform-provider-google/issues/6031

**Comment by sebastianortizs4n** [comment]
The solution use `google-beta` provider 3.17.0

**Comment by morgante** [comment]
Just to confirm, it sounds like this is fixed if you upgrade to the latest provider version?

In that case I'm going to close this issue.

**Comment by jmymy** [comment]
I am still seeing this behavior on an existing cluster with nodelocal cache disabled.

 ```+ 1.16.8-gke.4
Terraform v0.12.24
+ provider.google v3.17.0
+ provider.google-beta v3.17.0

+ dns_cache_config { # forces replacement
              + enabled = false
            }
```

**Comment by jmymy** [comment]
according to the repo, the fix didnt make it in the v3.17.0 release 
https://github.com/terraform-providers/terraform-provider-google-beta/blob/v3.17.0/google-beta/resource_container_cluster.go#L263

**Comment by sebastianortizs4n** [comment]
Ohh man, sorry about that. What I did was enabled it through the gcloud web, changed the config to true, removed the cluster from the state and import it again.

**Comment by morgante** [comment]
If someone does want to switch this in the module by updating to a dynamic block, I'm happy to review/merge.

**Comment by jmymy** [comment]
I asked on the original PR and they said it’ll be fixed in the 3.18 release

**Comment by jmymy** [comment]
looks like it made it.. will test tomorrow
 https://github.com/terraform-providers/terraform-provider-google-beta/releases/tag/v3.18.0

**Comment by bharathkkb** [comment]
@jmymy has this been resolved?
We may need to look applying this workaround to make it dynamic if it is still persisting.
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/497#discussion_r416106688

**Comment by jmymy** [comment]
is fixed. just tested

**Comment by mdaslamansari** [comment]
Is it available for AKS as well? If not, any work arounds?
